//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VerbosIrregulares
{
    using System;
    using System.Collections.Generic;
    
    public partial class VerbosIrregulare
    {
        public int id { get; set; }
        public string base_form { get; set; }
        public string past_form { get; set; }
        public string past_participle { get; set; }
        public string translate { get; set; }
        public string status { get; set; }
        public Nullable<int> prioridade { get; set; }
    }
}
